# vim: set expandtab ts=2 sw=2 sts=2:

- name: reload systemd
  shell: "systemctl daemon-reload"
  become: true
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version >= "7"

- name: reload PAT
  service: name=PAT state=reloaded
  become: true


