# vim: set expandtab ts=2 sts=2 sw=2:

- hosts: %HOSTS
  # playbook will stop after first error
  any_errors_fatal: true
  gather_facts: no
  vars:
    VAR: ""
  tasks:
  - name: task1
    ....
  - name: ...
    shell: git rev-parse HEAD
    args:
      chdir: "{{ path }}"
    register: new_head
    changed_when: "new_head.rc != 0"
    check_mode: no

- hosts: %HOSTS
  # need to detect centos7 
  gather_facts: yes
  vars:
    webconf_git_repo: %GIT
  roles:
    - {role: %ROLE, VAR_FOR_ROLE: false, ANOTHER_VAR: "some",  when: "new_head.stdout != base_head.stdout"  }

- hosts: %HOSTS
  gather_facts: yes
  tasks:

  - name: Try to reload nginx
    ...

